### ISSUE TITLE
Change business stage question

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/wealthmap#34]
Current:
![image](https://cloud.githubusercontent.com/assets/2693690/21234770/e33fda4a-c2a8-11e6-8f72-e658dc9a1031.png)

- [ ] Change to checkboxes instead of radio buttons (there used to be a "both" option, so it seems like this would be possible?)
- [x] Change "Tailor your results to the stage of your business." to "Is your business up and running, or you just starting and not yet in operation?"
- [x] Capitalize inputs (how is there no `text-transform:sentence-case` css value??)

**Comment by cweems** [comment]
Going to leave that first checkbox as is!
